### PR TITLE
flwq39 最后使用了rsa 加密

### PR DESCRIPTION
**Pull request by gg11011011**
public static String toSub(String  str ){
        if( str.length()>11){
            return str.substring(0,11);
        }else if( str.length() >2){
            return str.substring(0,2);
        }
        return str;
    }

    public static String flwq39(String k1, String k2, String k5) {

//        String k1 ="key1";
//        String k2 ="key2";
        String k3 = "";
        String k4 = "";
//        String k5 ="yzmSj";
        String k6 = "";
        k3 = encrypt(encode(k1 + k2));
        k4 = encode(k2);
        k6 = encode(encrypt(k1));
        k4 = encrypt(k4 + k5 + k6);

        k4 = checkVatQueryNormal(k1,k2,k3,k4,k5,k6);

        String k7 = gen(moveTo( encrypt( toSub(gen(k1, k2)))),
                (moveTo( toSub(k1 + k3 + k4))).length() * 7 +
                        encode(encrypt(  toSub(encode(toSub(k3) + k2 + encode(k4)))))
        ).toUpperCase();

        // 1,2,3,4,7

        k1 = encrypt(k3 + k4 + k7);
        k7 = encrypt(encrypt(moveTo( toSub( encode(k2 + k3) +  gen(k2, k7)  ) ) )
               +
                gen( toSub(encode(k1)), encrypt(k4.toUpperCase()).length() * 7 + "")
                ).toUpperCase();

        String k8 = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXY6ndiMJE7wF0qg9emVQik7FnCBidCr8V+yG/++iN/CwV0Rfe81wnjg2I23nbLJVuT63Y1T4x2etNr58BTHuzrCRy8gj3HPaS0GSGuiN7EWI1s0Bg6N78nvStPxeinyD8Qh3Bqa+5Z014nbOqn20kW4d3efLAeI7A6yc2uMPvfwIDAQAB";
        String k9 = "";
        try {
            k9 = RsaNewUtil.encrypt(k7, k8);
        } catch (Exception e) {
            e.printStackTrace();
        }

        return k9;
    }

    public static String publicKey(String fpdm, String fphm, String yzmSj) {
        String[] a = new String[]{"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
        String[] b = new String[]{"0", "9", "2", "8", "4", "5", "6", "7", "3", "1"};
        int c = Integer.valueOf(fpdm.substring(2, 3));
        String d = a[Integer.valueOf(b[c])];
        String e = encrypt(d + a[2] + "i" + encrypt(yzmSj));

        String f = encrypt(fphm + moveTo(fpdm.substring(0, 11)) + moveTo(e)) +
                encode(fphm + moveTo(encrypt(fphm + e.length())).toUpperCase()) +
                gen(fphm.substring(0, 2), (fpdm + e).length() * 7 + "").toUpperCase();
        f = encrypt(f);
        return f;
    }

    public static String checkVatQueryNormal (String k1,String k2,String k3,String k4,String k5,String k6){
        k1 = hxxa(k1,k2,k3);
        k2 = hxxb(k1,k2,k3,k4,k5,hxxa(k6,k5,k1));
        k3 = hxxc(k1,k2,k3,k4,k5,k6);
        k4=  hxxd(k1,k4,k3,k2,k5,k6);
        k5 = hxxe(k1,k2,k3,k4,k5,k6);

        k6 = hxxd(k5,k2,k3,k4,k1,k1);

        String ke =  encrypt(encrypt(k5+k6)
                    + encrypt(
                    ( encode(  toSub(""+gen(k4,k6).length()*7 ) ) + toSub( encode( encrypt( k3+k5 ) ) ) )
                        +
                       encode(encrypt( k5 + encode( toSub(k1+k2+k6 )+k1 + encode(k6) ).length()*7  ))

                    ) ).toUpperCase();
        return ke;
    }

    public static String hxxa (String k1,String k2,String k3){

        String k = encrypt( gen(k1,toSub(k1)) +k2.length()*7 + encrypt( toSub((k2+k3)) +
                gen(k3, moveTo(k1+k2).length()*7+"") ) ).toUpperCase();

        return k;
    }

    public static String hxxb (String k1,String k2,String k3,String k4,String k5, String k6){
        // k6 =  checkVatQueryNormal . hxxa(k6,k5,k1)

        String k = encrypt( encrypt( moveTo(  toSub(encode(k2 +k3) + gen(k2,k6) ) )   )
                +
                gen(  toSub(encode(k1+k5))  ,  encrypt(k4.toUpperCase()).length()*7+"" )
            ).toUpperCase();

        return k;
    }
    public static String hxxc (String k1,String k2,String k3,String k4,String k5, String k6){

        String k =   encrypt((k2 +moveTo( toSub((k1+k4)) ) )  +  moveTo(k6) )  +
                encode(k5 + moveTo( encrypt( k2 + k6.length()) ).toUpperCase() )

                + gen( toSub(k3) , ""+  (k1+k6).length()*7   ).toUpperCase()
            ;

        return k;
    }

    public static String hxxd (String k1,String k2,String k3,String k4,String k5, String k6){
        String k =  encrypt( (k6.length() + toSub(( k2 + k6 + k3 )) )+k6) +
                gen( (k1+k5).length()*7 +""  ,   k2.length()+ k5 )
                +   gen( k2,k6+k4 ).toUpperCase();

        return k;
    }

    private static String hxxe(String k1, String k2, String k3, String k4, String k5, String k6) {
        String k =
                encrypt(k2 + encrypt(   toSub(((k1+k5).length()*7 +k6.toUpperCase()))) +moveTo( toSub(k6))  ) +
                moveTo(encrypt(k1+k2+k6)+ encrypt( moveTo( k2 + k6.length() )).toUpperCase()  )
                +
                encrypt( toSub((k2+k4)) + (k1+( encrypt(k6+k3))).length()*7   ).toUpperCase()
        ;

        return k;
    }

### CODE REVIEW

**Comment by gg11011011** [comment]
我对比过 源码，里面只看到了 gen ，
 public static String gen(String n, String c) {
        String d = encrypt(n);
        String i = encrypt(n) + c;
        String h = "402880bd5c76101f015c903ee811504e";
        return encrypt(d + i + h + n.length()).toUpperCase();
    }

**Comment by BB-fat** [comment]
太棒了！你可以先Fork这个项目然后在你那边修改后再向我的master分支发起PR嘛，这样方便我直接讲你的代码融入到这个项目中，感谢！

**Comment by gg11011011** [comment]
唉，我不会

**Comment by BB-fat** [comment]
你可以参考一下这篇文章
https://juejin.im/post/5cb3f2546fb9a068b367879b
PR成功之后你就也是这个项目的贡献者了，期待你的加入。
另外，可否加一下微信或QQ，方便联络，可以通过邮箱告诉我你的账号。

**Comment by TongJin123** [comment]
image
我改成python代码，是有问题的，生成的flwq39长度和抓包的不一致

**Comment by FortuneStar** [comment]
> public static String toSub(String str ){
> if( str.length()>11){
> return str.substring(0,11);
> }else if( str.length() >2){
> return str.substring(0,2);
> }
> return str;
> }
> 
> ```
> public static String flwq39(String k1, String k2, String k5) {
> ```
> 
> // String k1 ="key1";
> // String k2 ="key2";
> String k3 = "";
> String k4 = "";
> // String k5 ="yzmSj";
> String k6 = "";
> k3 = encrypt(encode(k1 + k2));
> k4 = encode(k2);
> k6 = encode(encrypt(k1));
> k4 = encrypt(k4 + k5 + k6);
> 
> ```
>     k4 = checkVatQueryNormal(k1,k2,k3,k4,k5,k6);
> 
>     String k7 = gen(moveTo( encrypt( toSub(gen(k1, k2)))),
>             (moveTo( toSub(k1 + k3 + k4))).length() * 7 +
>                     encode(encrypt(  toSub(encode(toSub(k3) + k2 + encode(k4)))))
>     ).toUpperCase();
> 
>     // 1,2,3,4,7
> 
>     k1 = encrypt(k3 + k4 + k7);
>     k7 = encrypt(encrypt(moveTo( toSub( encode(k2 + k3) +  gen(k2, k7)  ) ) )
>            +
>             gen( toSub(encode(k1)), encrypt(k4.toUpperCase()).length() * 7 + "")
>             ).toUpperCase();
> 
>     String k8 = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXY6ndiMJE7wF0qg9emVQik7FnCBidCr8V+yG/++iN/CwV0Rfe81wnjg2I23nbLJVuT63Y1T4x2etNr58BTHuzrCRy8gj3HPaS0GSGuiN7EWI1s0Bg6N78nvStPxeinyD8Qh3Bqa+5Z014nbOqn20kW4d3efLAeI7A6yc2uMPvfwIDAQAB";
>     String k9 = "";
>     try {
>         k9 = RsaNewUtil.encrypt(k7, k8);
>     } catch (Exception e) {
>         e.printStackTrace();
>     }
> 
>     return k9;
> }
> 
> 
> public static String publicKey(String fpdm, String fphm, String yzmSj) {
>     String[] a = new String[]{"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
>     String[] b = new String[]{"0", "9", "2", "8", "4", "5", "6", "7", "3", "1"};
>     int c = Integer.valueOf(fpdm.substring(2, 3));
>     String d = a[Integer.valueOf(b[c])];
>     String e = encrypt(d + a[2] + "i" + encrypt(yzmSj));
> 
>     String f = encrypt(fphm + moveTo(fpdm.substring(0, 11)) + moveTo(e)) +
>             encode(fphm + moveTo(encrypt(fphm + e.length())).toUpperCase()) +
>             gen(fphm.substring(0, 2), (fpdm + e).length() * 7 + "").toUpperCase();
>     f = encrypt(f);
>     return f;
> }
> 
> 
> 
> public static String checkVatQueryNormal (String k1,String k2,String k3,String k4,String k5,String k6){
>     k1 = hxxa(k1,k2,k3);
>     k2 = hxxb(k1,k2,k3,k4,k5,hxxa(k6,k5,k1));
>     k3 = hxxc(k1,k2,k3,k4,k5,k6);
>     k4=  hxxd(k1,k4,k3,k2,k5,k6);
>     k5 = hxxe(k1,k2,k3,k4,k5,k6);
> 
>     k6 = hxxd(k5,k2,k3,k4,k1,k1);
> 
>     String ke =  encrypt(encrypt(k5+k6)
>                 + encrypt(
>                 ( encode(  toSub(""+gen(k4,k6).length()*7 ) ) + toSub( encode( encrypt( k3+k5 ) ) ) )
>                     +
>                    encode(encrypt( k5 + encode( toSub(k1+k2+k6 )+k1 + encode(k6) ).length()*7  ))
> 
>                 ) ).toUpperCase();
>     return ke;
> }
> 
> 
> public static String hxxa (String k1,String k2,String k3){
> 
>     String k = encrypt( gen(k1,toSub(k1)) +k2.length()*7 + encrypt( toSub((k2+k3)) +
>             gen(k3, moveTo(k1+k2).length()*7+"") ) ).toUpperCase();
> 
> 
>     return k;
> }
> 
> 
> public static String hxxb (String k1,String k2,String k3,String k4,String k5, String k6){
>     // k6 =  checkVatQueryNormal . hxxa(k6,k5,k1)
> 
>     String k = encrypt( encrypt( moveTo(  toSub(encode(k2 +k3) + gen(k2,k6) ) )   )
>             +
>             gen(  toSub(encode(k1+k5))  ,  encrypt(k4.toUpperCase()).length()*7+"" )
>         ).toUpperCase();
> 
> 
>     return k;
> }
> public static String hxxc (String k1,String k2,String k3,String k4,String k5, String k6){
> 
>     String k =   encrypt((k2 +moveTo( toSub((k1+k4)) ) )  +  moveTo(k6) )  +
>             encode(k5 + moveTo( encrypt( k2 + k6.length()) ).toUpperCase() )
> 
> 
>             + gen( toSub(k3) , ""+  (k1+k6).length()*7   ).toUpperCase()
>         ;
> 
>     return k;
> }
> 
> public static String hxxd (String k1,String k2,String k3,String k4,String k5, String k6){
>     String k =  encrypt( (k6.length() + toSub(( k2 + k6 + k3 )) )+k6) +
>             gen( (k1+k5).length()*7 +""  ,   k2.length()+ k5 )
>             +   gen( k2,k6+k4 ).toUpperCase();
> 
>     return k;
> }
> 
> private static String hxxe(String k1, String k2, String k3, String k4, String k5, String k6) {
>     String k =
>             encrypt(k2 + encrypt(   toSub(((k1+k5).length()*7 +k6.toUpperCase()))) +moveTo( toSub(k6))  ) +
>             moveTo(encrypt(k1+k2+k6)+ encrypt( moveTo( k2 + k6.length() )).toUpperCase()  )
>             +
>             encrypt( toSub((k2+k4)) + (k1+( encrypt(k6+k3))).length()*7   ).toUpperCase()
>     ;
> 
>     return k;
> }
> ```

moveTo函数在哪里呀

**Pull request closed without merging**
